### ISSUE TITLE
[Chrome] [Edge] - Create a Widget.

### ISSUE THREAD

**Issue by iBuilderLive** [TNotifier/Issues#39] opened 2015-09-27 03:43 UTC
I've tested in both Chrome and MS Edge but don't think it matters... the problem is here 
"Column 'hosts_text' cannot be null"  - your missing the HOST ALERT completely. both in the "show" section (basic tab) and on the TEXT tab.  please add hosting alerts.. I like em.  :dart: 

While creating a widget for HITBOX that would contain ALERTS.. follows, subs, and donations..., after filling in all the required info.. then clicking the create widget button, the following error message is the result;

**Comment by Oyed** [comment] 2015-09-27 12:41
Thanks - simple fix that I'll implement tomorrow. The issue is that Hitbox users don't have Host Alerts so it's hidden, but the Widget creation expects it.

**Comment by Oyed** [comment] 2015-09-27 15:24
Fixed in the latest revision of Alpha.

**Closed by Oyed** 2015-09-27 15:24 UTC
Labels: confirmed bug, hitbox
