### ISSUE TITLE
My media uploading issue #1

### ISSUE THREAD

**Issue by JoFont** [TNotifier/Issues#29] opened 2015-09-14 16:12 UTC
When you click upload and choose for instance an image but then select a font, this happens:
https://gyazo.com/9f0ff10fe43539f817a8a46c696d788c
After that a reload is not enough to get the bug out, you need to relog

**Comment by Oyed** [comment] 2015-09-14 16:20
Duplicate of #30

**Closed by Oyed** 2015-09-14 16:20 UTC
